name: Python Testing and Azure Blob Upload
 
on:
  push:
    branches:
      - azure-storage-pipeline
 
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # List of Python versions to test against
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
 
    - name: Run tests
      run: |
        python -m unittest discover -s test  
 
#   upload-to-azure:
#     needs: run-tests  # This job runs only if the run-tests job succeeds
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
 
#     - name: Upload files to Azure Blob Storage
#       uses: bacongobbler/azure-blob-storage-upload@v1.1.1
#       with:
#         source_dir: 'path_to_your_files'
#         container_name: 'your_container_name'
#         connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
#         sync: false