name: CI

on:
  push:
    branches:
      - azure-storage-pipeline

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Checking changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Upload changed files to Azure Blob Storage
        if: ${{ steps.changed-files.outputs.any_files_changed == 'true' }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Loop through changed files and upload each one to Azure Blob Storage
            for file in ${ALL_CHANGED_FILES}; do
              echo "Uploading $file to Azure Blob Storage..."
              # Replace 'your-container' and 'your-blob-name' with actual values
            az storage blob upload --account-name docsvisionify --container-name docs-images --file "each_scenario_details/$file" --name "$file" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
              echo "$file uploaded successfully."
            done
