name: CI

on:
  push:
    branches:
      - azure-storage-pipeline

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Checking changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check if scenarios.json is modified
        id: scenarios-json-changed
        run: |
          if grep -q "scenarios.json" <<< "$ALL_CHANGED_FILES"; then
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: Upload scenarios.json to Azure Blob Storage
        if: env.modified == 'true'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [ "$file" = "scenarios.json" ]; then
                echo "Uploading $file to Azure Blob Storage..."
                az storage blob upload --account-name docsvisionify --container-name docs-images --file "$file" --name "$file" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
                echo "$file uploaded successfully."
              fi
            done
