name: Python Testing and Azure Blob Upload

on:
  push:
    branches:
      - azure-storage-pipeline
  pull_request:
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run tests
        run: |
          python -m unittest discover -s test
  
  check-and-upload:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Check for changes in a specific folder
        id: check_changes
        run: |
          PREVIOUS_COMMIT=$(git rev-parse --short HEAD~1)
          CURRENT_COMMIT=$(git rev-parse --short HEAD~1)
          CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT $CURRENT_COMMIT -- each_scenario_details/)
              
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected in the specific folder."
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          else
            echo "Changes detected in the specific folder."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
            echo "$CHANGED_FILES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi
          
      - name: Upload
        if: steps.check_changes.outputs.CHANGES_DETECTED == 'true'
        run: |
          for file in $CHANGED_FILES; do
            az storage blob upload --account-name docsvisionify --container-name docs-images --file "each_scenario_details/$file" --name "$file" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
          done
