name: Python Testing and Azure Blob Upload

on:
  push:
    branches:
      - azure-storage-pipeline
  pull_request:
    types: [closed]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
<<<<<<< HEAD
          python-version: '3.10'  # Ensure this is the required Python version for your project.
  
=======
          python-version: '3.10'  # Specify your Python version

>>>>>>> 244dcb29897b9957ae80626ee738c53124e78e85
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run tests
        run: |
          python -m unittest discover -s test
  
  check-and-upload:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> 244dcb29897b9957ae80626ee738c53124e78e85
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this contains JSON with clientId, clientSecret, subscriptionId, and tenantId.
  
      - name: Check for changes in a specific folder
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} path/to/your/specific/folder)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected in the specific folder."
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          else
            echo "Changes detected in the specific folder."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
            echo "$CHANGED_FILES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi
<<<<<<< HEAD
  
=======

>>>>>>> 244dcb29897b9957ae80626ee738c53124e78e85
      - name: Upload
        if: env.CHANGES_DETECTED == 'true'
        run: |
          for file in $CHANGED_FILES; do
            az storage blob upload --account-name your_account_name --container-name your_container_name --file path/to/your/specific/folder/$file --name $file --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          done
