
name: Python Testing and Azure Blob Upload

on:
  push:
    branches:
      - azure-storage-pipeline  # Define the branches where this workflow will run

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s test

  upload-to-azure:
    needs: test  # This job will run only if the 'test' job succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload files to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'each_scenario_details/'  # Replace with your directory path
          container_name: 'docs-images/'  # Replace with your Azure container name
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          sync: false
