
name: Python Testing and Azure Blob Upload

on:
  push:
    branches:
      - azure-storage-pipeline  # Define the branches where this workflow will run

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s test

  upload-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
         
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Check for file changes
        id: file_changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD each_scenario_details)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes in 'each_scenario_details'"
            echo "changed_files=none" >> $GITHUB_ENV
          else
            echo "Files changed: $CHANGED_FILES"
            echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
          fi
         
      - name: Upload changed files to Azure Blob storage
        if: env.changed_files != 'none'
        run: |
          for file in ${{ env.changed_files }}
          do
            az storage blob upload --account-name docsvisionify --container-name docs-images --file $file --name $file --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          done

