name: Upload scenarios.json to Azure Blob Storage

on:
  push:
    branches:
      - azure-storage-pipeline

jobs:
  upload_to_azure_blob_storage:
    runs-on: ubuntu-latest
    name: Upload scenarios.json if modified
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check if scenarios.json is modified
        id: scenarios-json-changed
        run: |
          if grep -q "scenarios.json" <<< "${{ steps.changed-files.outputs.all_changed_files }}"; then
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "modified=false" >> $GITHUB_ENV
          fi

      - name: Upload scenarios.json to Azure Blob Storage
        if: env.modified == 'true'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Uploading scenarios.json to Azure Blob Storage..."
            az storage blob upload --account-name docsvisionify --container-name docs-images --file "scenarios.json" --name "scenarios.json" --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" --overwrite
            echo "scenarios.json uploaded successfully."
